# Generated by Django 6.0.6 on 2026-07-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.CharField(max_length=100)),
                ('passport', models.ImageField(upload_to='passports')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talmidin.classname')),
            ],
        ),
    ]
