# Generated by Django 6.0.6 on 2026-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talmidin', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classname',
            name='subjects',
            field=models.ManyToManyField(to='talmidin.subject'),
        ),
    ]
