# Generated by Django 6.0.6 on 2026-07-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talmidin', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CA1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('CA2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('TEST', models.DecimalField(decimal_places=2, max_digits=4)),
                ('EXAMS', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talmidin.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talmidin.subject')),
            ],
        ),
    ]
